{{- $snappass := .Values.snappass -}}
{{- if not $snappass.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snappass.fullname" . }}
  labels:
    {{- include "snappass.labels" . | nindent 4 }}
type: Opaque
data:
  secretKey: {{ if $snappass.secretKey }}{{ $snappass.secretKey | b64enc }}{{ else }}{{ randAlphaNum 40 | b64enc }}{{ end }}
{{- end }}
