{{- if not .Values.redis.enabled }}
{{- $redis := .Values.snappass.redis -}}
{{- if not $redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "snappass.fullname" . }}-redis"
  labels:
    {{- include "snappass.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ $redis.password | b64enc }}
{{- end }}
{{- end }}
